


class ConnectionString(object):

    def __init__(self):
        self.connectUrloffline = # PUT HERE THE CONNECTION STRING FOR THE DATABASE WITH USER, PASSWORD and PORT FOR THE OFFLINE DATABASE

	self.connectUrlonline = # PUT HERE THE CONNECTION STRING FOR THE DATABASE WITH USER, PASSWORD and PORT FOR THE ONLINE DATABASE

connectUrloffline =	# PUT HERE THE CONNECTION STRING FOR THE DATABASE WITH USER, PASSWORD and PORT FOR THE OFFLINE DATABASE

connectUrlonline =  # PUT HERE THE CONNECTION STRING FOR THE DATABASE WITH USER, PASSWORD and PORT FOR THE ONLINE DATABASE