class ConnectionString(object):
    connectUrloffline = # PUT HERE THE CONNECTION STRING FOR THE DATABASE WITH USER, PASSWORD and PORT FOR THE OFFLINE DATABASE
    connectUrlonline =  # PUT HERE THE CONNECTION STRING FOR THE DATABASE WITH USER, PASSWORD and PORT FOR THE ONLINE DATABASE
